# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import github_rpc_pb2 as github__rpc__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in github_rpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GitHubRpcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListPullRequests = channel.unary_unary(
                '/openclaw.skills.github.GitHubRpc/ListPullRequests',
                request_serializer=github__rpc__pb2.ListPullRequestsRequest.SerializeToString,
                response_deserializer=github__rpc__pb2.ListPullRequestsResponse.FromString,
                _registered_method=True)
        self.ViewPullRequest = channel.unary_unary(
                '/openclaw.skills.github.GitHubRpc/ViewPullRequest',
                request_serializer=github__rpc__pb2.ViewPullRequestRequest.SerializeToString,
                response_deserializer=github__rpc__pb2.ViewPullRequestResponse.FromString,
                _registered_method=True)
        self.CheckPullRequest = channel.unary_unary(
                '/openclaw.skills.github.GitHubRpc/CheckPullRequest',
                request_serializer=github__rpc__pb2.CheckPullRequestRequest.SerializeToString,
                response_deserializer=github__rpc__pb2.CheckPullRequestResponse.FromString,
                _registered_method=True)
        self.CreatePullRequest = channel.unary_unary(
                '/openclaw.skills.github.GitHubRpc/CreatePullRequest',
                request_serializer=github__rpc__pb2.CreatePullRequestRequest.SerializeToString,
                response_deserializer=github__rpc__pb2.CreatePullRequestResponse.FromString,
                _registered_method=True)
        self.MergePullRequest = channel.unary_unary(
                '/openclaw.skills.github.GitHubRpc/MergePullRequest',
                request_serializer=github__rpc__pb2.MergePullRequestRequest.SerializeToString,
                response_deserializer=github__rpc__pb2.MergePullRequestResponse.FromString,
                _registered_method=True)
        self.ListIssues = channel.unary_unary(
                '/openclaw.skills.github.GitHubRpc/ListIssues',
                request_serializer=github__rpc__pb2.ListIssuesRequest.SerializeToString,
                response_deserializer=github__rpc__pb2.ListIssuesResponse.FromString,
                _registered_method=True)
        self.CreateIssue = channel.unary_unary(
                '/openclaw.skills.github.GitHubRpc/CreateIssue',
                request_serializer=github__rpc__pb2.CreateIssueRequest.SerializeToString,
                response_deserializer=github__rpc__pb2.CreateIssueResponse.FromString,
                _registered_method=True)
        self.CloseIssue = channel.unary_unary(
                '/openclaw.skills.github.GitHubRpc/CloseIssue',
                request_serializer=github__rpc__pb2.CloseIssueRequest.SerializeToString,
                response_deserializer=github__rpc__pb2.CloseIssueResponse.FromString,
                _registered_method=True)
        self.ListWorkflowRuns = channel.unary_unary(
                '/openclaw.skills.github.GitHubRpc/ListWorkflowRuns',
                request_serializer=github__rpc__pb2.ListWorkflowRunsRequest.SerializeToString,
                response_deserializer=github__rpc__pb2.ListWorkflowRunsResponse.FromString,
                _registered_method=True)
        self.ViewWorkflowRun = channel.unary_unary(
                '/openclaw.skills.github.GitHubRpc/ViewWorkflowRun',
                request_serializer=github__rpc__pb2.ViewWorkflowRunRequest.SerializeToString,
                response_deserializer=github__rpc__pb2.ViewWorkflowRunResponse.FromString,
                _registered_method=True)
        self.RerunWorkflowRun = channel.unary_unary(
                '/openclaw.skills.github.GitHubRpc/RerunWorkflowRun',
                request_serializer=github__rpc__pb2.RerunWorkflowRunRequest.SerializeToString,
                response_deserializer=github__rpc__pb2.RerunWorkflowRunResponse.FromString,
                _registered_method=True)
        self.GitHubApi = channel.unary_unary(
                '/openclaw.skills.github.GitHubRpc/GitHubApi',
                request_serializer=github__rpc__pb2.GitHubApiRequest.SerializeToString,
                response_deserializer=github__rpc__pb2.GitHubApiResponse.FromString,
                _registered_method=True)


class GitHubRpcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListPullRequests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewPullRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckPullRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePullRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MergePullRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListIssues(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateIssue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseIssue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkflowRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewWorkflowRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RerunWorkflowRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GitHubApi(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GitHubRpcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListPullRequests': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPullRequests,
                    request_deserializer=github__rpc__pb2.ListPullRequestsRequest.FromString,
                    response_serializer=github__rpc__pb2.ListPullRequestsResponse.SerializeToString,
            ),
            'ViewPullRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewPullRequest,
                    request_deserializer=github__rpc__pb2.ViewPullRequestRequest.FromString,
                    response_serializer=github__rpc__pb2.ViewPullRequestResponse.SerializeToString,
            ),
            'CheckPullRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckPullRequest,
                    request_deserializer=github__rpc__pb2.CheckPullRequestRequest.FromString,
                    response_serializer=github__rpc__pb2.CheckPullRequestResponse.SerializeToString,
            ),
            'CreatePullRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePullRequest,
                    request_deserializer=github__rpc__pb2.CreatePullRequestRequest.FromString,
                    response_serializer=github__rpc__pb2.CreatePullRequestResponse.SerializeToString,
            ),
            'MergePullRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.MergePullRequest,
                    request_deserializer=github__rpc__pb2.MergePullRequestRequest.FromString,
                    response_serializer=github__rpc__pb2.MergePullRequestResponse.SerializeToString,
            ),
            'ListIssues': grpc.unary_unary_rpc_method_handler(
                    servicer.ListIssues,
                    request_deserializer=github__rpc__pb2.ListIssuesRequest.FromString,
                    response_serializer=github__rpc__pb2.ListIssuesResponse.SerializeToString,
            ),
            'CreateIssue': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateIssue,
                    request_deserializer=github__rpc__pb2.CreateIssueRequest.FromString,
                    response_serializer=github__rpc__pb2.CreateIssueResponse.SerializeToString,
            ),
            'CloseIssue': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseIssue,
                    request_deserializer=github__rpc__pb2.CloseIssueRequest.FromString,
                    response_serializer=github__rpc__pb2.CloseIssueResponse.SerializeToString,
            ),
            'ListWorkflowRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkflowRuns,
                    request_deserializer=github__rpc__pb2.ListWorkflowRunsRequest.FromString,
                    response_serializer=github__rpc__pb2.ListWorkflowRunsResponse.SerializeToString,
            ),
            'ViewWorkflowRun': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewWorkflowRun,
                    request_deserializer=github__rpc__pb2.ViewWorkflowRunRequest.FromString,
                    response_serializer=github__rpc__pb2.ViewWorkflowRunResponse.SerializeToString,
            ),
            'RerunWorkflowRun': grpc.unary_unary_rpc_method_handler(
                    servicer.RerunWorkflowRun,
                    request_deserializer=github__rpc__pb2.RerunWorkflowRunRequest.FromString,
                    response_serializer=github__rpc__pb2.RerunWorkflowRunResponse.SerializeToString,
            ),
            'GitHubApi': grpc.unary_unary_rpc_method_handler(
                    servicer.GitHubApi,
                    request_deserializer=github__rpc__pb2.GitHubApiRequest.FromString,
                    response_serializer=github__rpc__pb2.GitHubApiResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openclaw.skills.github.GitHubRpc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('openclaw.skills.github.GitHubRpc', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GitHubRpc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListPullRequests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openclaw.skills.github.GitHubRpc/ListPullRequests',
            github__rpc__pb2.ListPullRequestsRequest.SerializeToString,
            github__rpc__pb2.ListPullRequestsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewPullRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openclaw.skills.github.GitHubRpc/ViewPullRequest',
            github__rpc__pb2.ViewPullRequestRequest.SerializeToString,
            github__rpc__pb2.ViewPullRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckPullRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openclaw.skills.github.GitHubRpc/CheckPullRequest',
            github__rpc__pb2.CheckPullRequestRequest.SerializeToString,
            github__rpc__pb2.CheckPullRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePullRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openclaw.skills.github.GitHubRpc/CreatePullRequest',
            github__rpc__pb2.CreatePullRequestRequest.SerializeToString,
            github__rpc__pb2.CreatePullRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MergePullRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openclaw.skills.github.GitHubRpc/MergePullRequest',
            github__rpc__pb2.MergePullRequestRequest.SerializeToString,
            github__rpc__pb2.MergePullRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListIssues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openclaw.skills.github.GitHubRpc/ListIssues',
            github__rpc__pb2.ListIssuesRequest.SerializeToString,
            github__rpc__pb2.ListIssuesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateIssue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openclaw.skills.github.GitHubRpc/CreateIssue',
            github__rpc__pb2.CreateIssueRequest.SerializeToString,
            github__rpc__pb2.CreateIssueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseIssue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openclaw.skills.github.GitHubRpc/CloseIssue',
            github__rpc__pb2.CloseIssueRequest.SerializeToString,
            github__rpc__pb2.CloseIssueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkflowRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openclaw.skills.github.GitHubRpc/ListWorkflowRuns',
            github__rpc__pb2.ListWorkflowRunsRequest.SerializeToString,
            github__rpc__pb2.ListWorkflowRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewWorkflowRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openclaw.skills.github.GitHubRpc/ViewWorkflowRun',
            github__rpc__pb2.ViewWorkflowRunRequest.SerializeToString,
            github__rpc__pb2.ViewWorkflowRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RerunWorkflowRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openclaw.skills.github.GitHubRpc/RerunWorkflowRun',
            github__rpc__pb2.RerunWorkflowRunRequest.SerializeToString,
            github__rpc__pb2.RerunWorkflowRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GitHubApi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openclaw.skills.github.GitHubRpc/GitHubApi',
            github__rpc__pb2.GitHubApiRequest.SerializeToString,
            github__rpc__pb2.GitHubApiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
